on:
  issue_comment:
    types: [created] ##When the comment is 'created' then check if it's part of pull request. if so, run.
name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  badpull:
    name: bad pull request
    if: github.event.issue.pull_request != '' && !contains(github.event.comment.body, '/rebase')
    steps:
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

